language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - setup=basic
    - APP_ENV=local
    - APP_DEBUG=true
    - APP_KEY=QfD91IE2MIdmkNucPly6UOe1w2gCZG6C
    - DB_CONNECTION=mysql
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

sudo: false

#install:
#- if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
#- if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
#- if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpunit